from handlers.login_handler import *
from handlers.cancel_handler import *
from handlers.logout_handler import *
from handlers.open_admin_panel_handler import *
from handlers.select_bot_handler import *
from handlers.create_bot_handler import *
from handlers.remove_bot_handler import *
from handlers.get_bots_list_handler import *
from handlers.assign_bot_handler import *
from handlers.take_away_bot_handler import *
from handlers.set_payment_date_handler import *
from handlers.prolong_bot_handler import *
from handlers.set_price_handler import *
from handlers.run_newsletter_handler import *
from handlers.ok_handler import *
from handlers.update_bot_handler import *
from handlers.add_dependencies_handler import *
from handlers.start_bot_handler import *
from handlers.stop_bot_handler import *
from handlers.restart_bot_handler import *
from handlers.download_bot_files_handler import *
from handlers.download_bot_logs_handler import *
